{
 "title": "MongoDB FTDC Performance Dashboard",
 "time": { "from": "2024-10-24T01:09:50.402Z", "to": "2024-10-24T05:06:50.991Z" },
 "panels": [
  { "title": "System Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"ftdc\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ftdc\")\r\n  |> filter(fn: (r) => r._field == \"systemMetrics.cpu.idle_ms\" or r._field == \"systemMetrics.cpu.user_ms\" or r._field == \"systemMetrics.cpu.iowait_ms\" or r._field == \"systemMetrics.cpu.nice_ms\" or r._field == \"systemMetrics.cpu.softirq_ms\" or r._field == \"systemMetrics.cpu.steal_ms\" or r._field == \"systemMetrics.cpu.system_ms\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> derivative(unit: 1s, nonNegative: true, columns: [\"systemMetrics.cpu.idle_ms\", \"systemMetrics.cpu.user_ms\", \"systemMetrics.cpu.iowait_ms\", \"systemMetrics.cpu.nice_ms\", \"systemMetrics.cpu.softirq_ms\", \"systemMetrics.cpu.steal_ms\", \"systemMetrics.cpu.system_ms\"])\r\n  |> map(fn: (r) => ({\r\n      _time: r._time,\r\n      idle_ms: r[\"systemMetrics.cpu.idle_ms\"],\r\n      user_ms: r[\"systemMetrics.cpu.user_ms\"],\r\n      iowait_ms: r[\"systemMetrics.cpu.iowait_ms\"],\r\n      nice_ms: r[\"systemMetrics.cpu.nice_ms\"],\r\n      softirq_ms: r[\"systemMetrics.cpu.softirq_ms\"],\r\n      steal_ms: r[\"systemMetrics.cpu.steal_ms\"],\r\n      system_ms: r[\"systemMetrics.cpu.system_ms\"],\r\n      total_ms: r[\"systemMetrics.cpu.idle_ms\"] + r[\"systemMetrics.cpu.user_ms\"] + r[\"systemMetrics.cpu.iowait_ms\"] + r[\"systemMetrics.cpu.nice_ms\"] + r[\"systemMetrics.cpu.softirq_ms\"] + r[\"systemMetrics.cpu.steal_ms\"] + r[\"systemMetrics.cpu.system_ms\"]\r\n  }))\r\n  |> map(fn: (r) => ({\r\n      _time: r._time,\r\n      user: 100.0 * float(v: r.user_ms) / float(v: r.total_ms),\r\n      system: 100.0 * float(v: r.system_ms) / float(v: r.total_ms),\r\n      nice: 100.0 * float(v: r.nice_ms) / float(v: r.total_ms),\r\n      idle: 100.0 * float(v: r.idle_ms) / float(v: r.total_ms),\r\n      iowait: 100.0 * float(v: r.iowait_ms) / float(v: r.total_ms),\r\n      softirq: 100.0 * float(v: r.softirq_ms) / float(v: r.total_ms),\r\n      steal: 100.0 * float(v: r.steal_ms) / float(v: r.total_ms)\r\n  }))"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "query": "from(bucket: \"ftdc\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ftdc\")\r\n  |> filter(fn: (r) =>\r\n    r[\"_field\"] == \"systemMetrics.memory.MemAvailable_kb\" or\r\n    r[\"_field\"] == \"systemMetrics.memory.MemFree_kb\" or\r\n    r[\"_field\"] == \"systemMetrics.memory.MemTotal_kb\" or\r\n    r[\"_field\"] == \"systemMetrics.memory.Buffers_kb\" or\r\n    r[\"_field\"] == \"systemMetrics.memory.Cached_kb\" or\r\n    r[\"_field\"] == \"systemMetrics.memory.Dirty_kb\"\r\n  )\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({\r\n    r with\r\n    usedMemory_kb: r[\"systemMetrics.memory.MemTotal_kb\"] - r[\"systemMetrics.memory.MemAvailable_kb\"]\r\n  }))\r\n  |> group(columns: [\"_field\"])\r\n  |> yield(name: \"memory_usage\")"
    }
   ]
  },
  {
   "title": "Disk IOPS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "query": "import \"strings\"\r\n\r\nfrom(bucket: \"ftdc\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ftdc\")\r\n  |> filter(fn: (r) =>\r\n    r._field =~ /^systemMetrics\\.disks\\..*\\.writes$/ or\r\n    r._field =~ /^systemMetrics\\.disks\\..*\\.reads$/\r\n  )\r\n  |> map(fn: (r) => ({\r\n      r with _field: strings.replaceAll(\r\n        v: r._field,\r\n        t: \"systemMetrics.disks.\",\r\n        u: \"\"\r\n      )\r\n  }))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> derivative(unit: 1s)"
    }
   ]
  },
  {
   "title": "Disk Total Wait Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "import \"strings\"\r\n\r\nfrom(bucket: \"ftdc\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ftdc\")\r\n  |> filter(fn: (r) => r._field =~ /^systemMetrics\\.disks\\..*\\.io_queued_ms$/ )\r\n  |> map(fn: (r) => ({r with _field: strings.replaceAll(v: strings.replaceAll(v: r._field, t: \"systemMetrics.disks.\", u: \"\"), t: \".io_queued_ms\", u: \"\" ) }))\r\n  |> group(columns: [\"_field\"])\r\n  |> difference(nonNegative: false, columns: [\"_value\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"diff\")"
    }
   ]
  },
  {
   "title": "Disk Utilization",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "import \"strings\"\r\n\r\nfrom(bucket: \"ftdc\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"ftdc\" and\r\n    r._field =~ /^systemMetrics\\.disks\\..*\\.io_time_ms$/\r\n  )\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> derivative(unit: 1ms, nonNegative: true)\r\n  |> map(fn: (r) => ({\r\n      r with _value: r._value * 100.0  // convert to percentage\r\n  }))\r\n  |> map(fn: (r) => ({\r\n      r with _field: strings.replaceAll(\r\n        v: strings.replaceAll(\r\n          v: r._field,\r\n          t: \"systemMetrics.disks.\",\r\n          u: \"\"\r\n        ),\r\n        t: \".io_time_ms\",\r\n        u: \"\"\r\n      )\r\n  }))"
    }
   ]
  },
  {
   "title": "TCP: InSegs / OutSegs",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "import \"strings\"\r\n\r\nfrom(bucket: \"ftdc\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ftdc\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"systemMetrics.netstat.Tcp:InSegs\" or r[\"_field\"] == \"systemMetrics.netstat.Tcp:OutSegs\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> derivative(unit: v.windowPeriod)\r\n  |> map(fn: (r) => ({r with _field: strings.replaceAll(v: strings.replaceAll(v: r._field, t: \"systemMetrics.netstat.Tcp:\", u: \"\"), t: \".health\", u: \"\") }))"
    }
   ]
  },
  {
   "title": "TCP Connection Issues",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "import \"strings\"\r\n\r\nfrom(bucket: \"ftdc\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ftdc\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"systemMetrics.netstat.Tcp:CurrEstab\" or r[\"_field\"] == \"systemMetrics.netstat.Tcp:EstabResets\" or r[\"_field\"] == \"systemMetrics.netstat.Tcp:OutRsts\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> derivative(unit: v.windowPeriod)\r\n  |> map(fn: (r) => ({r with _field: strings.replaceAll(v: strings.replaceAll(v: r._field, t: \"systemMetrics.netstat.Tcp:\", u: \"\"), t: \".health\", u: \"\") }))"
    }
   ]
  },
  {
   "title": "TCP Packet Loss or Corruption",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "import \"strings\"\r\n\r\nfrom(bucket: \"ftdc\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ftdc\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"systemMetrics.netstat.Tcp:InCsumErrors\" \r\n                    or r[\"_field\"] == \"systemMetrics.netstat.Tcp:InErrs\"\r\n                    or r[\"_field\"] == \"systemMetrics.netstat.Tcp:RetransSegs\"\r\n                    or r[\"_field\"] == \"systemMetrics.netstat.Ip:InDiscards\"\r\n                    or r[\"_field\"] == \"systemMetrics.netstat.Ip:OutDiscards\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> derivative(unit: v.windowPeriod)\r\n  |> map(fn: (r) => ({r with _field: strings.replaceAll(v: strings.replaceAll(v: r._field, t: \"systemMetrics.netstat.Tcp:\", u: \"\"), t: \".health\", u: \"\") }))\r\n  |> map(fn: (r) => ({r with _field: strings.replaceAll(v: strings.replaceAll(v: r._field, t: \"systemMetrics.netstat.Ip:\", u: \"\"), t: \".health\", u: \"\") }))"
    }
   ]
  },
  {
   "title": "Netstat: TCP",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "import \"strings\"\r\n\r\nfrom(bucket: \"ftdc\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ftdc\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"systemMetrics.netstat.Tcp:ActiveOpens\" or r[\"_field\"] == \"systemMetrics.netstat.Tcp:AttemptFails\" or r[\"_field\"] == \"systemMetrics.netstat.Tcp:EstabResets\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> derivative(unit: v.windowPeriod)\r\n  |> map(fn: (r) => ({r with _field: strings.replaceAll(v: strings.replaceAll(v: r._field, t: \"systemMetrics.netstat.Tcp:\", u: \"\"), t: \".health\", u: \"\") }))"
    }
   ]
  },
  {
   "title": "MongoDB - General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Server Uptime",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 157 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "query": "from(bucket: \"ftdc\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ftdc\")\r\n  |> filter(fn: (r) =>  r[\"_field\"] == \"serverStatus.uptime\" )\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)"
      }
     ]
    }
   ]
  },
  {
   "title": "MongoDB - Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connections",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 158 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "query": "import \"strings\"\r\n\r\nfrom(bucket: \"ftdc\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ftdc\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"serverStatus.connections.active\" or r[\"_field\"] == \"serverStatus.connections.current\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _field: strings.replaceAll(v: r._field, t: \"serverStatus.connections.\", u: \"\") }))\r\n  |> yield(name: \"last\")"
      }
     ]
    },
    {
     "title": "Asserts",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 158 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "query": "import \"strings\"\r\n\r\nfrom(bucket: \"ftdc\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ftdc\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"serverStatus.asserts.warning\" or r[\"_field\"] == \"serverStatus.asserts.user\" or r[\"_field\"] == \"serverStatus.asserts.rollovers\" or r[\"_field\"] == \"serverStatus.asserts.regular\" or r[\"_field\"] == \"serverStatus.asserts.msg\")\r\n  |> map(fn: (r) => ({ r with _field: strings.replaceAll(v: r._field, t: \"serverStatus.asserts.\", u: \"\") }))\r\n  |> derivative(unit: v.windowPeriod)\r\n    |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
      }
     ]
    },
    {
     "title": "Operations",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 158 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "query": "import \"strings\"\r\n\r\nfrom(bucket: \"ftdc\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ftdc\")\r\n  |> filter(fn: (r) => \r\n      r[\"_field\"] == \"serverStatus.opcounters.update\" or\r\n      r[\"_field\"] == \"serverStatus.opcounters.query\" or\r\n      r[\"_field\"] == \"serverStatus.opcounters.insert\" or\r\n      r[\"_field\"] == \"serverStatus.opcounters.getmore\" or\r\n      r[\"_field\"] == \"serverStatus.opcounters.delete\" or\r\n      r[\"_field\"] == \"serverStatus.opcounters.command\")\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _field: strings.replaceAll(v: r._field, t: \"serverStatus.opcounters.\", u: \"\") }))"
      }
     ]
    },
    {
     "title": "Operations Repl",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 235 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "query": "import \"strings\"\r\n\r\nfrom(bucket: \"ftdc\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ftdc\")\r\n  |> filter(fn: (r) => \r\n      r[\"_field\"] == \"serverStatus.opcountersRepl.update\" or\r\n      r[\"_field\"] == \"serverStatus.opcountersRepl.query\" or\r\n      r[\"_field\"] == \"serverStatus.opcountersRepl.insert\" or\r\n      r[\"_field\"] == \"serverStatus.opcountersRepl.getmore\" or\r\n      r[\"_field\"] == \"serverStatus.opcountersRepl.delete\" or\r\n      r[\"_field\"] == \"serverStatus.opcountersRepl.command\")\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _field: strings.replaceAll(v: r._field, t: \"serverStatus.opcountersRepl.\", u: \"\") }))"
      }
     ]
    },
    {
     "title": "Total Operations",
     "type": "timeseries",
     "description": "The total number of operations performed on the database since startup.\n\nreads - Total number of read operations performed on the database since startup.\n\nwrites - Total number of write operations performed on the database since startup.\n\ncommands - Total number of database commands performed on the database since startup.\n\ntransactions - Total number of database transactions performed on the database since startup.",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 235 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "query": "import \"strings\"\r\n\r\nfrom(bucket: \"ftdc\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ftdc\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"serverStatus.opLatencies.reads.ops\" or r[\"_field\"] == \"serverStatus.opLatencies.writes.ops\" or r[\"_field\"] == \"serverStatus.opLatencies.commands.ops\" )\r\n  |> derivative(unit: 1s)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({\r\n      r with\r\n      _field: strings.replaceAll(\r\n        v: strings.replaceAll(v: r._field, t: \"serverStatus.opLatencies.\", u: \"\"),\r\n        t: \".ops\",\r\n        u: \"\"\r\n      )\r\n  }))"
      }
     ]
    },
    {
     "title": "Latency",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 235 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "query": "import \"strings\"\r\n\r\nfrom(bucket: \"ftdc\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ftdc\")\r\n  |> filter(fn: (r) =>\r\n    r[\"_field\"] == \"serverStatus.opLatencies.reads.latency\" or\r\n    r[\"_field\"] == \"serverStatus.opLatencies.writes.latency\" or\r\n    r[\"_field\"] == \"serverStatus.opLatencies.commands.latency\"\r\n  )\r\n  |> derivative(unit: v.windowPeriod)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({\r\n      r with\r\n      _field: strings.replaceAll(\r\n        v: strings.replaceAll(v: r._field, t: \"serverStatus.opLatencies.\", u: \"\"),\r\n        t: \".latency\",\r\n        u: \"\"\r\n      )\r\n  }))"
      }
     ]
    },
    {
     "title": "Cursors",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 241 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "query": "import \"strings\"\r\n\r\nfrom(bucket: \"ftdc\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ftdc\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"serverStatus.metrics.cursor.open.noTimeout\" or r[\"_field\"] == \"serverStatus.metrics.cursor.open.pinned\" or r[\"_field\"] == \"serverStatus.metrics.cursor.open.total\" or r[\"_field\"] == \"serverStatus.metrics.cursor.timedOut\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _field: strings.replaceAll(v: r._field, t: \"serverStatus.metrics.cursor.\", u: \"\") }))"
      }
     ]
    },
    {
     "title": "Collection Scan",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 241 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "query": "import \"strings\"\r\n\r\nfrom(bucket: \"ftdc\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ftdc\")\r\n  |> filter(fn: (r) => \r\n    r[\"_field\"] == \"serverStatus.metrics.queryExecutor.collectionScans.total\" or \r\n    r[\"_field\"] == \"serverStatus.metrics.queryExecutor.collectionScans.nonTailable\"\r\n  )\r\n  |> derivative(unit: v.windowPeriod)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> pivot(\r\n    rowKey: [\"_time\"],\r\n    columnKey: [\"_field\"],\r\n    valueColumn: \"_value\"\r\n  )\r\n  |> map(fn: (r) => ({\r\n    _time: r._time,\r\n    total: r[\"serverStatus.metrics.queryExecutor.collectionScans.total\"],\r\n    nonTailable: r[\"serverStatus.metrics.queryExecutor.collectionScans.nonTailable\"],\r\n    tailable: r[\"serverStatus.metrics.queryExecutor.collectionScans.total\"] - r[\"serverStatus.metrics.queryExecutor.collectionScans.nonTailable\"]\r\n  }))\r\n  |> yield(name: \"collectionScanBreakdown\")"
      }
     ]
    },
    {
     "title": "Block Sorting",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 241 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "query": "import \"strings\"\r\n\r\nfrom(bucket: \"ftdc\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ftdc\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"serverStatus.metrics.operation.scanAndOrder\")\r\n  |> derivative(unit: v.windowPeriod)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _field: strings.replaceAll(v: r._field, t: \"serverStatus.metrics.operation.\", u: \"\") }))"
      }
     ]
    },
    {
     "title": "Write Conflicts",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 247 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "query": "import \"strings\"\r\n\r\nfrom(bucket: \"ftdc\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ftdc\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"serverStatus.metrics.operation.writeConflicts\")\r\n  |> derivative(unit: v.windowPeriod)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _field: strings.replaceAll(v: r._field, t: \"serverStatus.metrics.operation.\", u: \"\") }))"
      }
     ]
    },
    {
     "title": "TTL Delete",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 247 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "query": "import \"strings\"\r\n\r\nfrom(bucket: \"ftdc\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ftdc\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"serverStatus.metrics.ttl.deletedDocuments\")\r\n  |> derivative(unit: v.windowPeriod)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _field: strings.replaceAll(v: r._field, t: \"serverStatus.metrics.ttl.\", u: \"\") }))"
      }
     ]
    },
    {
     "title": "Write Concern",
     "type": "timeseries",
     "description": "w > 1: The total number of operations with a specified write concern (i.e. w) that wait for one or more members of a replica set to acknowledge the write operation (i.e. a w value greater than 1.)\n\nwtimeouts: The number of times that write concern operations have timed out as a result of the wtimeout threshold. This number increments for both default and non-default write concern specifications.",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 247 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "query": "from(bucket: \"ftdc\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ftdc\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"serverStatus.metrics.getLastError.wtime.num\")\r\n  |> derivative(unit: 1s)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)"
      },
      {
       "query": "from(bucket: \"ftdc\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ftdc\")\n  |> filter(fn: (r) => r[\"_field\"] == \"serverStatus.metrics.getLastError.wtimeouts\")\n  |> derivative(unit: 1s)\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)"
      }
     ]
    }
   ]
  },
  {
   "title": "MongoDB - WiredTiger",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "WiredTiger Concurrency Tickets Available",
     "type": "timeseries",
     "description": "Tickets Available Read displays the number of read tickets available to the WiredTiger storage engine. Read tickets represent the number of concurrent read operations allowed into the storage engine. When this value reaches zero, new read requests might queue until a read ticket becomes available.\n\nTickets Available Write displays the number of write tickets available to the WiredTiger storage engine. Write tickets represent the number of concurrent write operations allowed into the storage engine. When this value reaches zero, new write requests might queue until a write ticket becomes available.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 159 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "query": "import \"strings\"\r\n\r\nfrom(bucket: \"ftdc\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ftdc\")\r\n  |> filter(fn: (r) =>\r\n      r[\"_field\"] == \"serverStatus.wiredTiger.concurrentTransactions.write.available\" or\r\n      r[\"_field\"] == \"serverStatus.wiredTiger.concurrentTransactions.read.available\" or\r\n      r[\"_field\"] == \"queues.execution.write.available\" or\r\n      r[\"_field\"] == \"queues.execution.read.available\"\r\n  )\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({r with _field: strings.replaceAll(v: strings.replaceAll(v: strings.replaceAll(v: r._field, t: \"serverStatus.wiredTiger.concurrentTransactions.\", u: \"\" ), t: \"queues.execution.\", u: \"\" ), t: \".available\", u: \"\" ) }))"
      }
     ]
    },
    {
     "title": "WiredTiger Cache Activity",
     "type": "timeseries",
     "description": "read Into displays the rate in bytes per second of data read from disk into memory to service queries.\n\nwritten From  displays the rate in bytes per second of data written from memory into disk to service writes.",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 159 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "query": "from(bucket: \"ftdc\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ftdc\")\r\n  |> filter(fn: (r) =>  r[\"_field\"] == \"serverStatus.wiredTiger.cache.bytes written from cache\" or r[\"_field\"] == \"serverStatus.wiredTiger.cache.bytes read into cache\")\r\n  |> derivative(unit: 1s)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)"
      }
     ]
    },
    {
     "title": "WiredTiger Cache Bytes Evicted",
     "type": "timeseries",
     "description": "Clean vs dirty data\n\nClean refers to data in the cache that is identical to the version stored on disk.\nDirty refers to data in the cache that has been modified and needs to be reconciled with the data stored on the disk.\n\nClean vs dirty eviction\n\nIn the case of clean eviction, there is no dirty content on the page and it is directly removed from the memory. After that, the page remains solely on the disk unchanged.\nIn the case of dirty eviction, the dirty page goes through reconciliation. The obsolete content on the page is thrown out, the latest value goes to the data store and older values go to the history store.",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 159 },
     "fieldConfig": { "defaults": { "unit": "KiBs" } },
     "targets": [
      {
       "query": "from(bucket: \"ftdc\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ftdc\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"serverStatus.wiredTiger.cache.modified pages evicted\" or r[\"_field\"] == \"serverStatus.wiredTiger.cache.unmodified pages evicted\")\r\n  |> map(fn: (r) => ({ r with _value: r._value * 4 }))\r\n  |> derivative(unit: 1s)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)"
      }
     ]
    },
    {
     "title": "Queued Operations",
     "type": "timeseries",
     "description": "Read: Represents the number of read operations that are currently queued or waiting to be processed in MongoDB. This metric indicates the backlog of read operations that are waiting for available resources, such as CPU or I/O, to be executed. Monitoring the queued read operations helps you assess the workload on the system and identify potential bottlenecks or resource constraints that may impact read operation performance.\n\nWrite: Represents the number of write operations that are currently queued or waiting to be processed in MongoDB. This metric indicates the backlog of write operations that are waiting for available resources, such as CPU or I/O, to be executed. Monitoring the queued write operations helps you assess the workload on the system and identify potential bottlenecks or resource constraints that may impact write operation performance.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 191 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "query": "import \"strings\"\r\n\r\nfrom(bucket: \"ftdc\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ftdc\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"serverStatus.globalLock.currentQueue.writers\" or r[\"_field\"] == \"serverStatus.globalLock.currentQueue.readers\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _field: strings.replaceAll(v: r._field, t: \"serverStatus.globalLock.currentQueue.\", u: \"\") }))\r\n  |> yield(name: \"last\")\r\n"
      }
     ]
    },
    {
     "title": "Query Executor",
     "type": "timeseries",
     "description": "scanned: Represents the number of index keys examined during query execution in MongoDB. This metric indicates the count of index entries evaluated by the query engine while processing queries or find operations. Monitoring the number of keys examined helps you assess the efficiency of your queries and index usage. It allows you to optimize query execution, improve index selection, and reduce the overall number of index entries processed during query evaluation.\n\nscannedObjects: Represents the number of documents examined during query execution in MongoDB. This metric indicates the count of documents evaluated by the query engine while processing queries or find operations. Monitoring the number of documents examined helps you understand the extent of document scanning and processing during query execution. It allows you to optimize query performance, improve query plans, and reduce the overall number of documents processed during query evaluation.",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 191 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "query": "import \"strings\"\r\n\r\nfrom(bucket: \"ftdc\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ftdc\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"serverStatus.metrics.queryExecutor.scannedObjects\" or r[\"_field\"] == \"serverStatus.metrics.queryExecutor.scanned\")\r\n  |> derivative(unit: v.windowPeriod)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _field: strings.replaceAll(v: r._field, t: \"serverStatus.metrics.queryExecutor.\", u: \"\") }))"
      }
     ]
    },
    {
     "title": "Document Operations",
     "type": "timeseries",
     "description": "Returned: Represents the number of documents returned by read operations in MongoDB. This metric indicates the count of documents retrieved as a result of queries or find operations. Monitoring the number of returned documents helps you assess the efficiency and effectiveness of your read operations, allowing you to optimize query performance and ensure accurate retrieval of the desired data.\n\nUpdated: Represents the number of documents updated by write operations in MongoDB. This metric indicates the count of documents modified as a result of update operations. Monitoring the number of updated documents helps you track the frequency of updates and assess the impact of write operations on your data. It allows you to optimize update operations, ensure data consistency, and track the effectiveness of any modifications made to your documents.\n\nInserted: Represents the number of documents inserted by write operations in MongoDB. This metric indicates the count of new documents added to the database as a result of insert operations. Monitoring the number of inserted documents helps you track the rate of data creation or ingestion, assess data growth patterns, and ensure the proper functioning of your data insertion processes.\n\nDeleted: Represents the number of documents deleted by write operations in MongoDB. This metric indicates the count of documents removed from the database as a result of delete operations. Monitoring the number of deleted documents helps you track the frequency of data removal, assess data cleanup processes, and ensure the proper management of your data lifecycle.",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 191 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "query": "import \"strings\"\r\n\r\nfrom(bucket: \"ftdc\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ftdc\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"serverStatus.metrics.document.updated\" or r[\"_field\"] == \"serverStatus.metrics.document.returned\" or r[\"_field\"] == \"serverStatus.metrics.document.inserted\" or r[\"_field\"] == \"serverStatus.metrics.document.deleted\")\r\n  |> derivative(unit: v.windowPeriod)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _field: strings.replaceAll(v: r._field, t: \"serverStatus.metrics.document.\", u: \"\") }))"
      }
     ]
    },
    {
     "title": "FlowControl Engaged",
     "type": "timeseries",
     "description": "The number of times flow control has engaged. Flow control engages when the majority committed lag is greater than some percentage of the flowControlTargetLagSeconds.\n\nWhen run on a secondary, the returned number is a placeholder.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 197 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "query": "import \"strings\"\r\n\r\nfrom(bucket: \"ftdc\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ftdc\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"serverStatus.flowControl.isLagged\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> derivative(unit: v.windowPeriod)\r\n  |> map(fn: (r) => ({ r with _field: strings.replaceAll(v: r._field, t: \"serverStatus.flowControl.\", u: \"\") }))\r\n  |> yield(name: \"last\")"
      }
     ]
    },
    {
     "title": "WiredTiger Cache Capacity",
     "type": "timeseries",
     "description": "Used displays the total bytes cached in memory for serving reads and writes.\n\nThese metrics include both indexes and data from the working set.\n\nSustained high cache usage indicates the RAM is too small for your workloads. Optimize your queries to avoid frequent disk reads. If write operations make cache usage high, throttle them.\n\nDirty Cache: Indicates modified data that needs to be written to the data files via a checkpoint.",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 197 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "query": "from(bucket: \"ftdc\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ftdc\")\r\n  |> filter(fn: (r) =>  r[\"_field\"] == \"serverStatus.wiredTiger.cache.maximum bytes configured\"  or r[\"_field\"] == \"serverStatus.wiredTiger.cache.bytes currently in the cache\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)"
      },
      {
       "query": "from(bucket: \"ftdc\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ftdc\")\n  |> filter(fn: (r) =>  r[\"_field\"] == \"serverStatus.wiredTiger.cache.tracked dirty bytes in the cache\" )\n  |> map(fn: (r) => ({ r with _value: r._value}))\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
      }
     ]
    }
   ]
  },
  {
   "title": "MongoDB - Oplog",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Oplog Size",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 160 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "query": "import \"strings\"\r\nimport \"regexp\"\r\n\r\nfrom(bucket: \"ftdc\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ftdc\")\r\n  |> filter(fn: (r) =>\r\n      r[\"_field\"] == \"local.oplog.rs.stats.wiredTiger.block-manager.file bytes available for reuse\" or\r\n      r[\"_field\"] == \"local.oplog.rs.stats.storageStats.wiredTiger.block-manager.file bytes available for reuse\" or\r\n      r[\"_field\"] == \"local.oplog.rs.stats.storageSize\" or\r\n      r[\"_field\"] == \"local.oplog.rs.stats.storageStats.storageSize\" or\r\n      r[\"_field\"] == \"local.oplog.rs.stats.maxSize\" or\r\n      r[\"_field\"] == \"local.oplog.rs.stats.storageStats.maxSize\"\r\n  )\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => {cleanField = strings.replaceAll(v: strings.replaceAll(v: r._field, t: \"local.oplog.rs.stats.storageStats.\", u: \"local.oplog.rs.stats.\" ), t: \"local.oplog.rs.stats.\", u: \"\" ) isReuse = regexp.matchRegexpString(r: /file bytes available for reuse/, v: cleanField) newField = if cleanField == \"maxSize\" then \"Uncompressed Size\" else if cleanField == \"storageSize\" then \"Compressed Size\" else if isReuse then \"Fragmentation Size\" else cleanField return { r with _field: newField } }) |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "Oplog - Avg Obj Size",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 160 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "query": "import \"strings\"\r\n\r\nfrom(bucket: \"ftdc\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ftdc\")\r\n  |> filter(fn: (r) => \r\n      r[\"_field\"] == \"local.oplog.rs.stats.avgObjSize\" or\r\n      r[\"_field\"] == \"local.oplog.rs.stats.storageStats.avgObjSize\"\r\n  )\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({r with _field: strings.replaceAll(v: strings.replaceAll(v: strings.replaceAll(v: r._field, t: \"local.oplog.rs.stats.storageStats.\", u: \"local.oplog.rs.stats.\" ), t: \"local.oplog.rs.stats.\", u: \"\" ), t: \".health\", u: \"\" ) }))"
      }
     ]
    }
   ]
  },
  {
   "title": "MongoDB - ReplicaSet",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Replica Members State",
     "type": "timeseries",
     "description": "This metric reflects the current state of a MongoDB replica set member, where each member’s state is represented by a numeric code defined by MongoDB.\n\nIt helps determine whether a node is PRIMARY, SECONDARY, ARBITER, DOWN, etc.\n\nCommon State Codes:\n\n0 - STARTUP\n1 - PRIMARY\n2 - SECONDARY\n3 - RECOVERING\n5 - STARTUP2\n6 - UNKNOWN\n7 - ARBITER\n8 - DOWN\n9 - ROLLBACK\n10 - REMOVED",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 161 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "query": "import \"strings\"\r\n\r\nfrom(bucket: \"ftdc\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ftdc\")\r\n  |> filter(fn: (r) => r._field =~ /^replSetGetStatus\\.members\\..*\\.state$/)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({r with _field: strings.replaceAll(v: strings.replaceAll(v: r._field, t: \"replSetGetStatus.\", u: \"\"), t: \".health\", u: \"\") }))\r\n  |> yield(name: \"last\")"
      }
     ]
    },
    {
     "title": "Replica Members Ping",
     "type": "timeseries",
     "description": "This metric reflects the ping or communication latency between the primary node and each replica member in a MongoDB replica set. It is an indicator of network responsiveness and member availability within the cluster.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 175 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "query": "import \"strings\"\r\n\r\nfrom(bucket: \"ftdc\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ftdc\")\r\n  |> filter(fn: (r) => r[\"_field\"] =~ /replSetGetStatus\\.members\\.\\d+\\.pingMs/)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _field: strings.replaceAll(v: r._field, t: \"replSetGetStatus.\", u: \"\") }))"
      }
     ]
    },
    {
     "title": "Replica Members Health",
     "type": "timeseries",
     "description": "This metric indicates the health status of a MongoDB replica set member",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 175 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "query": "import \"strings\"\r\n\r\nfrom(bucket: \"ftdc\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ftdc\")\r\n  |> filter(fn: (r) => r._field =~ /^replSetGetStatus\\.members\\..*\\.health$/)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({r with _field: strings.replaceAll(v: strings.replaceAll(v: r._field, t: \"replSetGetStatus.\", u: \"\"), t: \".health\", u: \"\") }))\r\n  |> yield(name: \"last\")"
      }
     ]
    },
    {
     "title": "Replica Members Lag",
     "type": "timeseries",
     "description": "This metric represents the replication lag between the primary node and each secondary member in the MongoDB replica set. It measures how much time (in seconds) a replica member is behind the primary in applying the latest operations.",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 175 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "query": "from(bucket: \"ftdc\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ftdc\")\r\n  |> filter(fn: (r) => r[\"_field\"] =~ /replSetGetStatus\\.members\\.\\d+\\.lastAppliedWallTime|serverStatus\\.localTime/)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({\r\n      _time: r._time,\r\n      member_0: if exists r[\"replSetGetStatus.members.0.lastAppliedWallTime\"] then (float(v: r[\"serverStatus.localTime\"]) - float(v: r[\"replSetGetStatus.members.0.lastAppliedWallTime\"])) / 1000.0 else 0.0,\r\n      member_1: if exists r[\"replSetGetStatus.members.1.lastAppliedWallTime\"] then (float(v: r[\"serverStatus.localTime\"]) - float(v: r[\"replSetGetStatus.members.1.lastAppliedWallTime\"])) / 1000.0 else 0.0,\r\n      member_2: if exists r[\"replSetGetStatus.members.2.lastAppliedWallTime\"] then (float(v: r[\"serverStatus.localTime\"]) - float(v: r[\"replSetGetStatus.members.2.lastAppliedWallTime\"])) / 1000.0 else 0.0,\r\n      member_3: if exists r[\"replSetGetStatus.members.3.lastAppliedWallTime\"] then (float(v: r[\"serverStatus.localTime\"]) - float(v: r[\"replSetGetStatus.members.3.lastAppliedWallTime\"])) / 1000.0 else 0.0,\r\n      member_4: if exists r[\"replSetGetStatus.members.4.lastAppliedWallTime\"] then (float(v: r[\"serverStatus.localTime\"]) - float(v: r[\"replSetGetStatus.members.4.lastAppliedWallTime\"])) / 1000.0 else 0.0,\r\n      member_5: if exists r[\"replSetGetStatus.members.5.lastAppliedWallTime\"] then (float(v: r[\"serverStatus.localTime\"]) - float(v: r[\"replSetGetStatus.members.5.lastAppliedWallTime\"])) / 1000.0 else 0.0,\r\n      member_6: if exists r[\"replSetGetStatus.members.6.lastAppliedWallTime\"] then (float(v: r[\"serverStatus.localTime\"]) - float(v: r[\"replSetGetStatus.members.6.lastAppliedWallTime\"])) / 1000.0 else 0.0,\r\n      member_7: if exists r[\"replSetGetStatus.members.7.lastAppliedWallTime\"] then (float(v: r[\"serverStatus.localTime\"]) - float(v: r[\"replSetGetStatus.members.7.lastAppliedWallTime\"])) / 1000.0 else 0.0,\r\n      member_8: if exists r[\"replSetGetStatus.members.8.lastAppliedWallTime\"] then (float(v: r[\"serverStatus.localTime\"]) - float(v: r[\"replSetGetStatus.members.8.lastAppliedWallTime\"])) / 1000.0 else 0.0,\r\n      member_9: if exists r[\"replSetGetStatus.members.9.lastAppliedWallTime\"] then (float(v: r[\"serverStatus.localTime\"]) - float(v: r[\"replSetGetStatus.members.9.lastAppliedWallTime\"])) / 1000.0 else 0.0,\r\n  }))\r\n  |> yield(name: \"differences\")"
      }
     ]
    }
   ]
  },
  {
   "title": "Available Metrics Reference\t",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Available Metrics",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 162 },
     "targets": [
      {
       "query": "from(bucket: \"ftdc\")\n  |> range(start: 0)\n  |> last()\n  |> group(columns: [])\n  |> keep(columns: [\"_field\", \"_value\"])\n  |> rename(columns: {_field: \"Field\", _value: \"Latest Value\"})\n  |> sort(columns: [\"Field\"])"
      }
     ]
    }
   ]
  }
 ]
}